### ISSUE TITLE
ppr doesn't work in a windows environment due to SaferGenerator class usage due to fork

### ISSUE THREAD

**Issue by kobbled** [civol/ppr#2]
Hey @civol,

I am needing ppr to work in a windows environment, and wondering if you think this is possible? Do you think it would be possible to modify SaferGenerator to work on windows? I was trying to use `Proc::spawn` yesterday but I couldn't get it to work.

Thanks,

**Comment by civol** [comment]
Hi @kobbled 

Thank you for using ppr and for your comments and updates. I will try to fix ppr (and merge your suggestions) as soon as I can. If porting to windows is not too difficult I will try to do that this weekend.

Regards,

**Comment by kobbled** [comment]
Thanks @civol! Your efforts are much appreciated!

**Comment by civol** [comment]
Hi @kobbled

I merged your modifications, thank you for them.
Also, I reworked SafeGenerator so that it uses a single process (and therefore no fork is required).
It seems to work on my macOS and Windows environments.

Regards.

**Comment by kobbled** [comment]
Thank you so much @civol, it works! This saves my bacon. I couldn't find any other ruby based preprocessors that had as clean syntax, and a way to run ruby code! Workflow for the interpreter I'm developing couldn't allow for a docker container, as the eventual compiler is only windows based. 

If I can tip you for your hard work send me an address where I can send cash , or crypto!

If you are interested, I'm developing an interpreter (https://github.com/kobbled/tp_plus) for Fanuc robots (no affiliation) to abstract there teach pendent language. Currently  their language is missing a lot of core features you would expect in a language, and codes more at an assembly level than anything else.

**Comment by civol** [comment]
I am happy to be of service.

Thank you for the tip but it is enough for me if you find ppr useful. 

I am unfamiliar with robotics, but Fanuc TP looks awkward indeed. It reminds me a bit of some old languages like COBOL.
I have colleagues that have some work with robots, I do not know which kind of robot they use but they may be interested in TP+.

I wish you success with your project.
